/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/geo/footprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Footprint */
        get: operations["footprint_api_v1_geo_footprint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geo/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Geocode */
        post: operations["geocode_api_v1_geo_geocode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. No external dependencies are checked here.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solar/sun-position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sun Position */
        get: operations["sun_position_api_v1_solar_sun_position_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Footprint
         * @description A building outline as a ring of lat/lng vertices (source: OSM).
         */
        Footprint: {
            /** Points */
            points: components["schemas"]["LatLng"][];
            /**
             * Source
             * @default osm
             */
            source: string;
        };
        /** FootprintResponse */
        FootprintResponse: {
            footprint: components["schemas"]["Footprint"] | null;
        };
        /** GeocodeRequest */
        GeocodeRequest: {
            /** Query */
            query: string;
        };
        /** GeocodeResponse */
        GeocodeResponse: {
            /** Results */
            results: components["schemas"]["GeocodeResult"][];
        };
        /** GeocodeResult */
        GeocodeResult: {
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /** Label */
            label: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Postcode */
            postcode?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** LatLng */
        LatLng: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /**
         * SunPosition
         * @description Solar position in the pvlib frame: azimuth 0=N, 90=E, 180=S, 270=W.
         */
        SunPosition: {
            /**
             * Azimuth
             * @description Compass azimuth, degrees (0=N, 90=E, 180=S, 270=W).
             */
            azimuth: number;
            /**
             * Elevation
             * @description Apparent elevation above the horizon, degrees.
             */
            elevation: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    footprint_api_v1_geo_footprint_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FootprintResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    geocode_api_v1_geo_geocode_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeocodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    sun_position_api_v1_solar_sun_position_get: {
        parameters: {
            query: {
                lat: number;
                lng: number;
                /** @description ISO 8601 instant; naive is treated as UTC. */
                timestamp: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SunPosition"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
