// Public entrypoint for generated API types.
// `src/api.ts` is generated by `pnpm run codegen` from the FastAPI OpenAPI
// schema — never hand-edit it. Re-export the bits consumers actually use.
export type { paths, components, operations } from "./api";
